### ISSUE TITLE
Data file Location

### ISSUE THREAD

**Issue by sachooo** [vincentdchan/CubyText#2]
Where are my data files ? Need folder path for backup.

**Comment by vincentdchan** [comment]
It depends on your system:

On macOS: `~/Library/Application Support/CubyText/notebook.db`
On Linux: `~/.config/CubyText/notebook.db`
On Windows: `%APPDATA%/CubyText/notebook.db`

**Comment by vincentdchan** [comment]
I am making the official website, this infomation will be added to the website.

**Comment by vincentdchan** [comment]
[0.0.2 is released](https://github.com/vincentdchan/CubyText/releases/tag/0.0.2). And you can select the path to store your data now.

<img width="832" alt="Screen Shot 2022-09-17 at 22 26 14" src="https://user-images.githubusercontent.com/2352832/190862058-90bae2da-210f-4891-b6b1-1d132ee5a3e0.png">
